KEY_GUILD_NAME = "guild_name"
KEY_ENABLE_ATTACHMENTS = "enable_attachments"
KEY_ENABLE_URLS = "enable_urls"
KEY_ENABLE_MENTIONS = "enable_mentions"
KEY_START_DATE = "start_date"
KEY_END_DATE = "end_date"
KEY_SEND_TO = "channel_to_send_to"
KEY_SELECT_FROM = "channel_to_select_from"
